dist: trusty
language: node_js
node_js:
  - 12
install:
  - npm i
  - CI=true npm run coverage
branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "ridakaddir"
    token:
      secure: "NK31WIfKmseDLtCu7UfPogDrL/8535cCWkmf9zXtOAM33IoO2RcBE6P1NTkQVEBdVGE6fej7EWxzhg5m6Wu7TpoZ4unDNaUkdf5onbP/ow0HqUkQzVKZniJdAqRs5+hn544CKfcK8Jex5qeBLLiNfSikMIlc8OTUTQtmbbQjSKEDFmgSxFg7OkZHAnpDSW801SWNr4saZtPbMwkRNWoFnC9phAnQXaZbcRaLwFi9BeLXXB1mO8XZ2vhgCZM+a+URio7x0cRzr+Wz0FYCOdmj1ZH0+mccrxT7BxYxNh364Olz+LafSVlfs8QAzNr//PSTkW0b3FAD3VzMDye3dOLLDc0D6D4ac757/bUbGqR4akIG+RGoKnGbnIMpgEl8ARTKBkf1t8V3WWcP1FUOAmIUmpOUIp3EpSXkDGw0/jjsi/QHFE426bvh1vLhJU8SWtu934f/kmCpUiCX9X4QSZLKOQLZeMqD3PNTIVsGih7xGK/UzSTU8J7vJ/U2wnEwJpbB/3rl6nNznjdUNFF0hc8CDfy/Qw4xJ7t0eL404OvGCufqWEWTk7xes35AYRxuZG3JkY6zzu4tDebhySGzBj43lGdbB6rRnj0BmPk605WSgXP7EmAFKrfKbcK1jStU24kO1XsAXvTyyPi0i8REA6tqwA6/M8Ul38QHNiphhfI17Ms=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
